server:
  port: 8090

spring:
  application:
    name: account
  profiles:
    active: local # Spring Boot会自动去找application-local.yaml并把里面的配置合并进来，覆盖application.yaml的空值
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Sa-Token的基础配置
sa-token:
  token-name: Authorization # token传递的请求头名称，与接口文档一致
  timeout: 86400 # token有效期，单位秒，86400 即 24 小时
  is-concurrent: true # 是否允许统一账号多地登录
  is-share: false # 同一账号多地登录是否共享同一个token，若共享，任一端登出后另一端也会失效
  token-style: uuid # token生成风格，uuid格式